# Generated by Django 3.1 on 2020-08-17 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='u_age',
            field=models.IntegerField(default=0),
        ),
    ]
